# Generated by Django 4.1.1 on 2022-10-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='atividade_diaadia',
            field=models.CharField(default=False, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='certidao_trouxe_na_primeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='certidao_trouxe_na_segunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='certidao_vai_trazer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='cpf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='data_acolhida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='dependem_renda',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='endereco',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='estado_civil',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='idade_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='imovel_proprio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='numero_de_filhos_menores_de_15',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='obs',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='pessoas_especiais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='qual_bolsa',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='qual_doenca',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='quantos_familiares_trabalham',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='quem_doente',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='renda_mensal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='responsavel',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='retornos',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='rg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='total_renda',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='valor_aluguel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='pessoa.pessoa'),
        ),
    ]
