# Generated by Django 4.1.1 on 2022-11-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_contato_filiacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=256)),
                ('rg_ou_cpf', models.CharField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
                ('roupas', models.BooleanField(default=False)),
                ('calcados', models.BooleanField(default=False)),
                ('alimentos', models.BooleanField(default=False)),
                ('material_escolar', models.BooleanField(default=False)),
                ('bebe_mulher', models.BooleanField(default=False)),
                ('bebe_homem', models.BooleanField(default=False)),
                ('idade_bebe', models.IntegerField(max_length=1)),
                ('numero_bebe', models.IntegerField(max_length=10)),
                ('numero_calc_bebe', models.IntegerField(max_length=10)),
                ('obs_bebe', models.CharField(max_length=512)),
                ('infant_mulher', models.BooleanField(default=False)),
                ('quantidade_infant_mulher', models.BooleanField(default=False)),
                ('idades_mulher', models.BooleanField(default=False)),
                ('numero_mulher', models.IntegerField(max_length=10)),
                ('calc_numero_mulher', models.IntegerField(max_length=10)),
                ('infant_homem', models.BooleanField(default=False)),
                ('quantidade_infant_homem', models.BooleanField(default=False)),
                ('idades_homem', models.BooleanField(default=False)),
                ('numero_homem', models.IntegerField(max_length=10)),
                ('calc_numero_homem', models.IntegerField(max_length=10)),
                ('obs', models.CharField(max_length=512)),
                ('entregas_realizadas', models.CharField(max_length=4096)),
                ('nome_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='pessoa.pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='DadosPessoa',
        ),
        migrations.AlterField(
            model_name='contato',
            name='dependem_renda',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='idade',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='idade_1',
            field=models.CharField(blank=True, default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='contato',
            name='numero_de_filhos_menores_de_15',
            field=models.CharField(blank=True, default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='obs',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='contato',
            name='qual_bolsa',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contato',
            name='qual_doenca',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contato',
            name='quantos_familiares_trabalham',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='quem_doente',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contato',
            name='renda_mensal',
            field=models.IntegerField(blank=True, default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='retornos',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contato',
            name='total_renda',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='valor_aluguel',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
