# Generated by Django 4.1.1 on 2022-11-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_doacoes_delete_dadospessoa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doacoes',
        ),
    ]
