# Generated by Django 4.1.1 on 2022-11-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0006_delete_doacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=256)),
                ('rg_ou_cpf', models.CharField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
                ('roupas', models.BooleanField(default=False)),
                ('calcados', models.BooleanField(default=False)),
                ('alimentos', models.BooleanField(default=False)),
                ('material_escolar', models.BooleanField(default=False)),
                ('bebe_mulher', models.BooleanField(default=False)),
                ('bebe_homem', models.BooleanField(default=False)),
                ('idade_bebe', models.IntegerField(max_length=1)),
                ('numero_bebe', models.IntegerField(max_length=10)),
                ('numero_calc_bebe', models.IntegerField(max_length=10)),
                ('obs_bebe', models.CharField(max_length=512)),
                ('infant_mulher', models.BooleanField(default=False)),
                ('quantidade_infant_mulher', models.BooleanField(default=False)),
                ('idades_mulher', models.BooleanField(default=False)),
                ('numero_mulher', models.IntegerField(max_length=10)),
                ('calc_numero_mulher', models.IntegerField(max_length=10)),
                ('infant_homem', models.BooleanField(default=False)),
                ('quantidade_infant_homem', models.BooleanField(default=False)),
                ('idades_homem', models.BooleanField(default=False)),
                ('numero_homem', models.IntegerField(max_length=10)),
                ('calc_numero_homem', models.IntegerField(max_length=10)),
                ('obs', models.CharField(max_length=512)),
                ('entregas_realizadas', models.CharField(max_length=4096)),
                ('nome_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='pessoa.pessoa')),
            ],
        ),
    ]
