# Generated by Django 4.1.1 on 2022-11-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacoes',
            name='calcados',
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='calc_numero_homem',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='calc_numero_mulher',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='entregas_realizadas',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='idade_bebe',
            field=models.IntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='idades_homem',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='idades_mulher',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='infant_homem',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_bebe',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_calc_bebe',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_homem',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_mulher',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='obs',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='obs_bebe',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='quantidade_infant_homem',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='quantidade_infant_mulher',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
