# Generated by Django 4.1.1 on 2022-11-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_remove_doacoes_calcados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='idade_bebe',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_bebe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_calc_bebe',
            field=models.IntegerField(),
        ),
    ]
