# Generated by Django 4.1.1 on 2022-11-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_alter_doacoes_idade_bebe_alter_doacoes_numero_bebe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='quantidade_infant_homem',
            field=models.IntegerField(),
        ),
    ]
