# Generated by Django 4.1.1 on 2022-11-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0004_alter_doacoes_quantidade_infant_homem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='numero_calc_bebe',
            field=models.IntegerField(null=True),
        ),
    ]
