# Generated by Django 4.1.1 on 2022-11-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0005_alter_doacoes_numero_calc_bebe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='calc_numero_homem',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='entregas_realizadas',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='idades_mulher',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_bebe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_homem',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='numero_mulher',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='obs',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='quantidade_infant_homem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='quantidade_infant_mulher',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
