# Generated by Django 4.1.1 on 2022-11-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0007_alter_doacoes_nome_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='calcados',
            field=models.BooleanField(default=False),
        ),
    ]
